// Copyright 2024 ros2_controllers Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef THREE_WHEEL_DRIVE_CONTROLLER__THREE_WHEEL_DRIVE_CONTROLLER_HPP_
#define THREE_WHEEL_DRIVE_CONTROLLER__THREE_WHEEL_DRIVE_CONTROLLER_HPP_

#include <chrono>
#include <cmath>
#include <memory>
#include <queue>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "tf2_msgs/msg/tf_message.hpp"

#include "three_wheel_drive_controller/odometry.hpp"
#include "three_wheel_drive_controller/speed_limiter.hpp"

// auto-generated by generate_parameter_library
#include "three_wheel_drive_controller/three_wheel_drive_controller_parameters.hpp"

namespace three_wheel_drive_controller
{
using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

class ThreeWheelDriveController : public controller_interface::ControllerInterface
{
  using TwistStamped = geometry_msgs::msg::TwistStamped;

public:
  ThreeWheelDriveController();

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  CallbackReturn on_init() override;

  CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_error(const rclcpp_lifecycle::State & previous_state) override;

protected:
  // Wheel handle structures for front differential drive wheels
struct WheelHandle
{
  std::reference_wrapper<const hardware_interface::LoanedStateInterface> velocity_state;
  std::reference_wrapper<hardware_interface::LoanedCommandInterface> velocity_command;
};  // Rear wheel handles for traction and steering
  struct RearWheelHandle
  {
    std::reference_wrapper<const hardware_interface::LoanedStateInterface> velocity_state;
    std::reference_wrapper<hardware_interface::LoanedCommandInterface> velocity_command;
    std::reference_wrapper<const hardware_interface::LoanedStateInterface> position_state;
    std::reference_wrapper<hardware_interface::LoanedCommandInterface> position_command;
  };

  CallbackReturn get_wheel(
    const std::string & wheel_name, const std::vector<std::string> & wheel_names,
    std::vector<WheelHandle> & registered_handles);

  CallbackReturn get_rear_wheel(
    const std::string & rear_wheel_name, std::vector<RearWheelHandle> & registered_handles);

  /**
   * \brief Calculate three-wheel robot speeds
   * 
   * This function computes the individual wheel speeds for a three-wheel robot configuration:
   * - Two front wheels in differential drive configuration (left/right)
   * - One rear steered wheel
   *
   * \param linear_velocity Forward velocity at the front axle center (m/s)
   * \param angular_velocity Angular velocity around vertical axis (rad/s)
   * \param wheelbase Distance from front axle to rear wheel (m)  
   * \param track_width Distance between left and right front wheels (m)
   * \param[out] left_wheel_vel Left front wheel velocity (m/s)
   * \param[out] right_wheel_vel Right front wheel velocity (m/s)
   * \param[out] rear_wheel_vel Rear wheel velocity (m/s)
   * \param[out] rear_wheel_pos Rear wheel steering position (rad)
   */
  void calculate_three_wheel_kinematics(
    double linear_velocity, double angular_velocity,
    double wheelbase, double track_width,
    double & left_wheel_vel, double & right_wheel_vel, 
    double & rear_wheel_vel, double & rear_wheel_pos);

  // Parameters from ROS for three_wheel_drive_controller
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // Wheel handles
  std::vector<WheelHandle> registered_left_wheel_handles_;
  std::vector<WheelHandle> registered_right_wheel_handles_;
  std::vector<RearWheelHandle> registered_rear_wheel_handles_;

  // Odometry
  std::shared_ptr<Odometry> odometry_;

  std::shared_ptr<rclcpp::Publisher<nav_msgs::msg::Odometry>> odometry_publisher_ = nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::msg::Odometry>>
    realtime_odometry_publisher_ = nullptr;

  std::shared_ptr<rclcpp::Publisher<tf2_msgs::msg::TFMessage>> odometry_transform_publisher_ =
    nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<tf2_msgs::msg::TFMessage>>
    realtime_odometry_transform_publisher_ = nullptr;

  // Command subscriber
  bool subscriber_is_active_ = false;
  rclcpp::Subscription<TwistStamped>::SharedPtr velocity_command_subscriber_ = nullptr;
  realtime_tools::RealtimeThreadSafeBox<std::shared_ptr<TwistStamped>> received_velocity_msg_ptr_{nullptr};

  // Timeout to consider cmd_vel commands old  
  std::chrono::milliseconds cmd_vel_timeout_{500};

  // Speed limiters
  std::unique_ptr<SpeedLimiter> limiter_linear_;
  std::unique_ptr<SpeedLimiter> limiter_angular_;

  // Limited velocity publisher
  bool publish_limited_velocity_ = false;
  std::shared_ptr<rclcpp::Publisher<TwistStamped>> limited_velocity_publisher_ = nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<TwistStamped>>
    realtime_limited_velocity_publisher_ = nullptr;

  // Previous command for limiters
  std::queue<std::array<double, 2>> previous_commands_;

  rclcpp::Time previous_update_timestamp_{0};

  // publish rate limiter
  double publish_rate_ = 50.0;
  rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
  rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};

  bool reset();
  void halt();

private:
  void reset_buffers();
};

}  // namespace three_wheel_drive_controller

#endif  // THREE_WHEEL_DRIVE_CONTROLLER__THREE_WHEEL_DRIVE_CONTROLLER_HPP_